// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JJPerson.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class BasePerson;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum Person_Corpus

typedef GPB_ENUM(Person_Corpus) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  Person_Corpus_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  Person_Corpus_Universal = 0,
  Person_Corpus_Web = 1,
  Person_Corpus_Images = 2,
  Person_Corpus_Local = 3,
  Person_Corpus_News = 4,
  Person_Corpus_Products = 5,
  Person_Corpus_Video = 6,
};

GPBEnumDescriptor *Person_Corpus_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL Person_Corpus_IsValidValue(int32_t value);

#pragma mark - JJPersonRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface JJPersonRoot : GPBRootObject
@end

#pragma mark - BasePerson

typedef GPB_ENUM(BasePerson_FieldNumber) {
  BasePerson_FieldNumber_UserName = 1,
};

@interface BasePerson : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@end

#pragma mark - Person

typedef GPB_ENUM(Person_FieldNumber) {
  Person_FieldNumber_UserName = 1,
  Person_FieldNumber_UserAge = 2,
  Person_FieldNumber_Snippets = 3,
  Person_FieldNumber_Projects = 4,
  Person_FieldNumber_BasePerson = 5,
  Person_FieldNumber_Corpus = 6,
  Person_FieldNumber_BytesFields = 7,
  Person_FieldNumber_BasePersons = 8,
  Person_FieldNumber_TestBool = 9,
};

@interface Person : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@property(nonatomic, readwrite) int32_t userAge;

@property(nonatomic, readwrite, copy, null_resettable) NSString *snippets;

@property(nonatomic, readwrite, strong, null_resettable) BasePerson *basePersons;
/** Test to see if @c basePersons has been set. */
@property(nonatomic, readwrite) BOOL hasBasePersons;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32ObjectDictionary<NSString*> *projects;
/** The number of items in @c projects without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger projects_Count;

@property(nonatomic, readwrite, strong, null_resettable) BasePerson *basePerson;
/** Test to see if @c basePerson has been set. */
@property(nonatomic, readwrite) BOOL hasBasePerson;

@property(nonatomic, readwrite) Person_Corpus corpus;

@property(nonatomic, readwrite, copy, null_resettable) NSData *bytesFields;

@property(nonatomic, readwrite) BOOL testBool;

@end

/**
 * Fetches the raw value of a @c Person's @c corpus property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Person_Corpus_RawValue(Person *message);
/**
 * Sets the raw value of an @c Person's @c corpus property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPerson_Corpus_RawValue(Person *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
